//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoToSQLSync
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RulesEntities : DbContext
    {
        public RulesEntities()
            : base("name=RulesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SAL_SalaryType_Mst> SAL_SalaryType_Mst { get; set; }
        public virtual DbSet<OfficeTypeMaster> OfficeTypeMasters { get; set; }
    }
}
