//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoToSQLSync
{
    using System;
    using System.Collections.Generic;

    [MongoDB.Bson.Serialization.Attributes.BsonIgnoreExtraElements]
    public partial class OfficeTypeMaster
    {
        public int officeTypeID { get; set; }
        public string officename { get; set; }
        public string code { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> Fk_OfficeCategoryId { get; set; }
    }

    [MongoDB.Bson.Serialization.Attributes.BsonIgnoreExtraElements]
    public partial class OfficeTypeMaster1
    {
        // public MongoDB.Bson.ObjectId _id { get; set; }
        public int officeTypeID { get; set; }
        public string officename { get; set; }
        public string code { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> Fk_OfficeCategoryId { get; set; }
    }
}
