//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MongoToSQLSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAL_SalaryType_Mst
    {
        public short pk_saltypeid { get; set; }
        public string saltype { get; set; }
        public short orderby { get; set; }
        public bool active { get; set; }
    }
}
